# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.contrib.gis.db import models

# Create your models here.
class district_boundaries(models.Model):
    district_n = models.CharField(max_length=100, blank=True, null=True)
    district_c = models.CharField(max_length=3, blank=True, null=True)
    geom = models.MultiPolygonField(srid=4326, blank=True, null=True)

    def __str__(self):
        return self.district_n

class taluka_boundaries(models.Model):
    district_n = models.CharField(max_length=100)
    district_c = models.CharField(max_length=3)
    taluka_nam = models.CharField(max_length=50)
    taluka_cod = models.CharField(max_length=5)
    geom = models.MultiPolygonField(srid=4326)

    def __str__(self):
        return self.taluka_nam

class state_maharashtra(models.Model):
    st_nm = models.CharField(max_length=75)
    st_cen_cd = models.CharField(max_length=2)
    dt_cen_cd = models.CharField(max_length=2)
    district = models.CharField(max_length=50)
    geom = models.MultiPolygonField(srid=4326)

    def __str__(self):
        return self.st_nm

class SchoolInfo(models.Model):
    txtbkyear = models.CharField(max_length=200, blank=True, null=True)
    workdays_hsec = models.CharField(max_length=200, blank=True, null=True)
    spltrg_place = models.CharField(max_length=200, blank=True, null=True)
    aad_f = models.CharField(max_length=200, blank=True, null=True)
    acstartmnth = models.CharField(max_length=200, blank=True, null=True)
    othrooms = models.CharField(max_length=200, blank=True, null=True)
    subexp_f = models.CharField(max_length=200, blank=True, null=True)
    cce_yn = models.CharField(max_length=200, blank=True, null=True)
    toiletwater_b = models.CharField(max_length=200, blank=True, null=True)
    edu_block = models.CharField(max_length=200, blank=True, null=True)
    up_comp_set_fre_textbookrec = models.CharField(max_length=200, blank=True, null=True)
    toiletwater_g = models.CharField(max_length=200, blank=True, null=True)
    clgoods = models.CharField(max_length=200, blank=True, null=True)
    subexp_m = models.CharField(max_length=200, blank=True, null=True)
    par_in_pos_sec = models.CharField(max_length=200, blank=True, null=True)
    clsunderconst = models.CharField(max_length=200, blank=True, null=True)
    handwash_yn = models.CharField(max_length=200, blank=True, null=True)
    totcomp_func = models.CharField(max_length=200, blank=True, null=True)
    acname = models.CharField(max_length=200, blank=True, null=True)
    yearrecog = models.CharField(max_length=200, blank=True, null=True)
    schmgths = models.CharField(max_length=200, blank=True, null=True)
    smg_e = models.CharField(max_length=200, blank=True, null=True)
    meds1 = models.CharField(max_length=200, blank=True, null=True)
    latsec = models.CharField(max_length=200, blank=True, null=True)
    meds4 = models.CharField(max_length=200, blank=True, null=True)
    pcr_shared = models.CharField(max_length=200, blank=True, null=True)
    sec_resi_school_yn = models.CharField(max_length=200, blank=True, null=True)
    p_playmat_av = models.CharField(max_length=200, blank=True, null=True)
    toiletg_func = models.CharField(max_length=200, blank=True, null=True)
    spltrg_totev = models.CharField(max_length=200, blank=True, null=True)
    londeg = models.CharField(max_length=200, blank=True, null=True)
    smg_r = models.CharField(max_length=200, blank=True, null=True)
    spltrg_py_enrolled_b = models.CharField(max_length=200, blank=True, null=True)
    txtbkmnth = models.CharField(max_length=200, blank=True, null=True)
    sch_category = models.CharField(max_length=200, blank=True, null=True)
    schhrschild_upr = models.CharField(max_length=200, blank=True, null=True)
    clmajors = models.CharField(max_length=200, blank=True, null=True)
    clminorhs = models.CharField(max_length=200, blank=True, null=True)
    urinals_b = models.CharField(max_length=200, blank=True, null=True)
    toilet_g = models.CharField(max_length=200, blank=True, null=True)
    workdays_sec = models.CharField(max_length=200, blank=True, null=True)
    smc_yn = models.CharField(max_length=200, blank=True, null=True)
    boardhsec = models.CharField(max_length=200, blank=True, null=True)
    ebmc_m = models.CharField(max_length=200, blank=True, null=True)
    lang1 = models.CharField(max_length=200, blank=True, null=True)
    spltrg_material_yn = models.CharField(max_length=200, blank=True, null=True)
    lang3 = models.CharField(max_length=200, blank=True, null=True)
    lang2 = models.CharField(max_length=200, blank=True, null=True)
    workdays_upr = models.CharField(max_length=200, blank=True, null=True)
    furntch = models.CharField(max_length=200, blank=True, null=True)
    spltrg_by = models.CharField(max_length=200, blank=True, null=True)
    clgood = models.CharField(max_length=200, blank=True, null=True)
    clmajor_tnt = models.CharField(max_length=200, blank=True, null=True)
    bookbank_yn = models.CharField(max_length=200, blank=True, null=True)
    bankname = models.CharField(max_length=200, blank=True, null=True)
    reg_in_pos_hsec = models.CharField(max_length=200, blank=True, null=True)
    clgood_tnt = models.CharField(max_length=200, blank=True, null=True)
    water = models.CharField(max_length=200, blank=True, null=True)
    toiletb_func = models.CharField(max_length=200, blank=True, null=True)
    schhrschild_pr = models.CharField(max_length=200, blank=True, null=True)
    handrails = models.CharField(max_length=200, blank=True, null=True)
    anganwadi_yn = models.CharField(max_length=200, blank=True, null=True)
    medh4 = models.CharField(max_length=200, blank=True, null=True)
    medh3 = models.CharField(max_length=200, blank=True, null=True)
    medh2 = models.CharField(max_length=200, blank=True, null=True)
    medh1 = models.CharField(max_length=200, blank=True, null=True)
    spltrg_cy_provided_b = models.CharField(max_length=200, blank=True, null=True)
    totcls11 = models.CharField(max_length=200, blank=True, null=True)
    totcls12 = models.CharField(max_length=200, blank=True, null=True)
    spltrg_py_provided_b = models.CharField(max_length=200, blank=True, null=True)
    assembly_constituency = models.CharField(max_length=200, blank=True, null=True)
    spltrg_cy_provided_g = models.CharField(max_length=200, blank=True, null=True)
    spltrg_py_provided_g = models.CharField(max_length=200, blank=True, null=True)
    ac_yn = models.CharField(max_length=200, blank=True, null=True)
    relminority_type = models.CharField(max_length=200, blank=True, null=True)
    municipality = models.CharField(max_length=200, blank=True, null=True)
    conti_e = models.CharField(max_length=200, blank=True, null=True)
    toiletb = models.CharField(max_length=200, blank=True, null=True)
    bankac_yn = models.CharField(max_length=200, blank=True, null=True)
    toiletd = models.CharField(max_length=200, blank=True, null=True)
    estdyear = models.CharField(max_length=200, blank=True, null=True)
    conti_r = models.CharField(max_length=200, blank=True, null=True)
    ptameeting = models.CharField(max_length=200, blank=True, null=True)
    statname = models.CharField(max_length=200, blank=True, null=True)
    txtbkrecd_yn = models.CharField(max_length=200, blank=True, null=True)
    lowclass = models.CharField(max_length=200, blank=True, null=True)
    website = models.CharField(max_length=200, blank=True, null=True)
    scst_f = models.CharField(max_length=200, blank=True, null=True)
    clmajor = models.CharField(max_length=200, blank=True, null=True)
    clsuconst12 = models.CharField(max_length=200, blank=True, null=True)
    furn_yn10 = models.CharField(max_length=200, blank=True, null=True)
    clsuconst10 = models.CharField(max_length=200, blank=True, null=True)
    clsuconst11 = models.CharField(max_length=200, blank=True, null=True)
    scst_m = models.CharField(max_length=200, blank=True, null=True)
    clminor_kuc = models.CharField(max_length=200, blank=True, null=True)
    smcbankac_yn = models.CharField(max_length=200, blank=True, null=True)
    spltrg_py_enrolled_g = models.CharField(max_length=200, blank=True, null=True)
    smcmem_f = models.CharField(max_length=200, blank=True, null=True)
    clmajorhs = models.CharField(max_length=200, blank=True, null=True)
    village = models.CharField(max_length=200, blank=True, null=True)
    pri_resi_school_yn = models.CharField(max_length=200, blank=True, null=True)
    rampsneeded_yn = models.CharField(max_length=200, blank=True, null=True)
    smcmem_m = models.CharField(max_length=200, blank=True, null=True)
    anganwadi_tch = models.CharField(max_length=200, blank=True, null=True)
    visitscrc = models.CharField(max_length=200, blank=True, null=True)
    sip_yn = models.CharField(max_length=200, blank=True, null=True)
    deo_m = models.CharField(max_length=200, blank=True, null=True)
    ramps_yn = models.CharField(max_length=200, blank=True, null=True)
    osrc_e = models.CharField(max_length=200, blank=True, null=True)
    totcls10 = models.CharField(max_length=200, blank=True, null=True)
    ifsc = models.CharField(max_length=200, blank=True, null=True)
    cityname = models.CharField(max_length=200, blank=True, null=True)
    campusplan_yn = models.CharField(max_length=200, blank=True, null=True)
    distu = models.CharField(max_length=200, blank=True, null=True)
    block_name = models.CharField(max_length=200, blank=True, null=True)
    aidrecd = models.CharField(max_length=200, blank=True, null=True)
    dists = models.CharField(max_length=200, blank=True, null=True)
    ppstudent = models.IntegerField(blank=True, null=True)
    up_palymat_av = models.CharField(max_length=200, blank=True, null=True)
    spltrg_evtrnd = models.CharField(max_length=200, blank=True, null=True)
    p_tle_av = models.CharField(max_length=200, blank=True, null=True)
    osrc_r = models.CharField(max_length=200, blank=True, null=True)
    medchk_yn = models.CharField(max_length=200, blank=True, null=True)
    relminority_yn = models.CharField(max_length=200, blank=True, null=True)
    clminors = models.CharField(max_length=200, blank=True, null=True)
    reg_tch_san_hsec = models.CharField(max_length=200, blank=True, null=True)
    smsparents_m = models.CharField(max_length=200, blank=True, null=True)
    totcls9 = models.CharField(max_length=200, blank=True, null=True)
    schmgt = models.CharField(max_length=200, blank=True, null=True)
    smsparents_f = models.CharField(max_length=200, blank=True, null=True)
    meds2 = models.CharField(max_length=200, blank=True, null=True)
    lonmin = models.CharField(max_length=200, blank=True, null=True)
    clgood_ppu = models.CharField(max_length=200, blank=True, null=True)
    up_tle_av = models.CharField(max_length=200, blank=True, null=True)
    meds3 = models.CharField(max_length=200, blank=True, null=True)
    ebmc_f = models.CharField(max_length=200, blank=True, null=True)
    schtypes = models.CharField(max_length=200, blank=True, null=True)
    yearrecogs = models.CharField(max_length=200, blank=True, null=True)
    deo_f = models.CharField(max_length=200, blank=True, null=True)
    shift_yn = models.CharField(max_length=200, blank=True, null=True)
    smschildrec_yn = models.CharField(max_length=200, blank=True, null=True)
    smcbank = models.CharField(max_length=200, blank=True, null=True)
    land4pground_yn = models.CharField(max_length=200, blank=True, null=True)
    electric_yn = models.CharField(max_length=200, blank=True, null=True)
    cwsnsch_yn = models.CharField(max_length=200, blank=True, null=True)
    ifsccode = models.CharField(max_length=200, blank=True, null=True)
    reg_tch_san_sec = models.CharField(max_length=200, blank=True, null=True)
    anganwadi_stu = models.CharField(max_length=200, blank=True, null=True)
    schhrstch_upr = models.CharField(max_length=200, blank=True, null=True)
    spltrg_type = models.CharField(max_length=200, blank=True, null=True)
    cal_yn = models.CharField(max_length=200, blank=True, null=True)
    pta_yn = models.CharField(max_length=200, blank=True, null=True)
    ccesec_yn = models.CharField(max_length=200, blank=True, null=True)
    ac_year = models.CharField(max_length=200, blank=True, null=True)
    smdc_yn = models.CharField(max_length=200, blank=True, null=True)
    custer_name = models.CharField(max_length=200, blank=True, null=True)
    pground_yn = models.CharField(max_length=200, blank=True, null=True)
    wsec25p_enrolled = models.CharField(max_length=200, blank=True, null=True)
    medinstr4 = models.CharField(max_length=200, blank=True, null=True)
    noinspect = models.CharField(max_length=200, blank=True, null=True)
    reg_in_pos_sec = models.CharField(max_length=200, blank=True, null=True)
    medinstr1 = models.CharField(max_length=200, blank=True, null=True)
    medinstr3 = models.CharField(max_length=200, blank=True, null=True)
    medinstr2 = models.CharField(max_length=200, blank=True, null=True)
    schhrstch_pr = models.CharField(max_length=200, blank=True, null=True)
    schname = models.CharField(max_length=200, blank=True, null=True)
    parents_m = models.CharField(max_length=200, blank=True, null=True)
    par_in_pos_up = models.CharField(max_length=200, blank=True, null=True)
    furn_yn9 = models.CharField(max_length=200, blank=True, null=True)
    visitsrtcwsn = models.CharField(max_length=200, blank=True, null=True)
    reg_in_pos_up = models.CharField(max_length=200, blank=True, null=True)
    parents_f = models.CharField(max_length=200, blank=True, null=True)
    spltrg_cy_enrolled_b = models.CharField(max_length=200, blank=True, null=True)
    clmajor_ppu = models.CharField(max_length=200, blank=True, null=True)
    hmroom_yn = models.CharField(max_length=200, blank=True, null=True)
    smcacname = models.CharField(max_length=200, blank=True, null=True)
    ccehsec_yn = models.CharField(max_length=200, blank=True, null=True)
    hostelboys = models.CharField(max_length=200, blank=True, null=True)
    par_in_pos_p = models.CharField(max_length=200, blank=True, null=True)
    tch_m = models.CharField(max_length=200, blank=True, null=True)
    bankacno = models.CharField(max_length=200, blank=True, null=True)
    sbc_yn = models.CharField(max_length=200, blank=True, null=True)
    latdeg = models.CharField(max_length=200, blank=True, null=True)
    yearrecogs_1 = models.CharField(max_length=200, blank=True, null=True)
    smdcmeeting = models.CharField(max_length=200, blank=True, null=True)
    ahm_f = models.CharField(max_length=200, blank=True, null=True)
    tlm_e = models.CharField(max_length=200, blank=True, null=True)
    ahm_m = models.CharField(max_length=200, blank=True, null=True)
    smcmeetings = models.CharField(max_length=200, blank=True, null=True)
    approachbyroad = models.CharField(max_length=200, blank=True, null=True)
    panchayat = models.CharField(max_length=200, blank=True, null=True)
    tot_m = models.CharField(max_length=200, blank=True, null=True)
    smcsmdc1_yn = models.CharField(max_length=200, blank=True, null=True)
    spltrg_cy_enrolled_g = models.CharField(max_length=200, blank=True, null=True)
    schtypehs = models.CharField(max_length=200, blank=True, null=True)
    clminor = models.CharField(max_length=200, blank=True, null=True)
    tot_f = models.CharField(max_length=200, blank=True, null=True)
    furn_yn11 = models.CharField(max_length=200, blank=True, null=True)
    cp_m = models.CharField(max_length=200, blank=True, null=True)
    hostelb_yn = models.CharField(max_length=200, blank=True, null=True)
    lonsec = models.CharField(max_length=200, blank=True, null=True)
    smcsdp_yn = models.CharField(max_length=200, blank=True, null=True)
    up_resi_school_yn = models.CharField(max_length=200, blank=True, null=True)
    par_in_pos_hsec = models.CharField(max_length=200, blank=True, null=True)
    cp_f = models.CharField(max_length=200, blank=True, null=True)
    clminor_tnt = models.CharField(max_length=200, blank=True, null=True)
    residential_type = models.CharField(max_length=200, blank=True, null=True)
    reg_in_pos_p = models.CharField(max_length=200, blank=True, null=True)
    ppsec_yn = models.CharField(max_length=200, blank=True, null=True)
    yearupgrdh = models.CharField(max_length=200, blank=True, null=True)
    smcnomlocal_f = models.CharField(max_length=200, blank=True, null=True)
    bldstatus = models.CharField(max_length=200, blank=True, null=True)
    block_name_1 = models.CharField(max_length=200, blank=True, null=True)
    workdays_pr = models.CharField(max_length=200, blank=True, null=True)
    smcnomlocal_m = models.CharField(max_length=200, blank=True, null=True)
    schcd = models.CharField(max_length=200, blank=True, null=True)
    upgrad_sec = models.CharField(max_length=200, blank=True, null=True)
    p_comp_set_fre_textbookrec = models.CharField(max_length=200, blank=True, null=True)
    reg_tch_san_p = models.CharField(max_length=200, blank=True, null=True)
    clrooms = models.CharField(max_length=200, blank=True, null=True)
    clsuconst9 = models.CharField(max_length=200, blank=True, null=True)
    librarian_yn = models.CharField(max_length=200, blank=True, null=True)
    bankbranch = models.CharField(max_length=200, blank=True, null=True)
    clmajor_kuc = models.CharField(max_length=200, blank=True, null=True)
    hm_f = models.CharField(max_length=200, blank=True, null=True)
    prevoccourse_yn = models.CharField(max_length=200, blank=True, null=True)
    eduvocguide_yn = models.CharField(max_length=200, blank=True, null=True)
    water_func_yn = models.CharField(max_length=200, blank=True, null=True)
    spltrng_yn = models.CharField(max_length=200, blank=True, null=True)
    hm_m = models.CharField(max_length=200, blank=True, null=True)
    wsec25p_applied = models.CharField(max_length=200, blank=True, null=True)
    stuadmitted = models.CharField(max_length=200, blank=True, null=True)
    reg_tch_san_up = models.CharField(max_length=200, blank=True, null=True)
    newspaper_yn = models.CharField(max_length=200, blank=True, null=True)
    schtype = models.CharField(max_length=200, blank=True, null=True)
    mtongue_yn = models.CharField(max_length=200, blank=True, null=True)
    upgrad_up = models.CharField(max_length=200, blank=True, null=True)
    highclass = models.CharField(max_length=200, blank=True, null=True)
    bookinlib = models.CharField(max_length=200, blank=True, null=True)
    hsec_resi_school_yn = models.CharField(max_length=200, blank=True, null=True)
    schmgts = models.CharField(max_length=200, blank=True, null=True)
    rururb = models.CharField(max_length=200, blank=True, null=True)
    latmin = models.CharField(max_length=200, blank=True, null=True)
    hostelgirls = models.CharField(max_length=200, blank=True, null=True)
    habitation_name = models.CharField(max_length=200, blank=True, null=True)
    clgoodhs = models.CharField(max_length=200, blank=True, null=True)
    clgood_kuc = models.CharField(max_length=200, blank=True, null=True)
    instr_rte_up = models.CharField(max_length=200, blank=True, null=True)
    visitsbrc = models.CharField(max_length=200, blank=True, null=True)
    boardsec = models.CharField(max_length=200, blank=True, null=True)
    aad_m = models.CharField(max_length=200, blank=True, null=True)
    ppteacher = models.IntegerField(blank=True, null=True)
    women_m = models.CharField(max_length=200, blank=True, null=True)
    tch_f = models.CharField(max_length=200, blank=True, null=True)
    tlm_r = models.CharField(max_length=200, blank=True, null=True)
    smcacno = models.CharField(max_length=200, blank=True, null=True)
    smcbankbranch = models.CharField(max_length=200, blank=True, null=True)
    land4cls_yn = models.CharField(max_length=200, blank=True, null=True)
    city = models.CharField(max_length=200, blank=True, null=True)
    furnstu = models.CharField(max_length=200, blank=True, null=True)
    distname = models.CharField(max_length=200, blank=True, null=True)
    bndrywall = models.CharField(max_length=200, blank=True, null=True)
    furn_yn12 = models.CharField(max_length=200, blank=True, null=True)
    hostelg_yn = models.CharField(max_length=200, blank=True, null=True)
    local_m = models.CharField(max_length=200, blank=True, null=True)
    pcr_maintained = models.CharField(max_length=200, blank=True, null=True)
    computer = models.CharField(max_length=200, blank=True, null=True)
    clminor_ppu = models.CharField(max_length=200, blank=True, null=True)
    local_f = models.CharField(max_length=200, blank=True, null=True)
    urinals_g = models.CharField(max_length=200, blank=True, null=True)

    def __str__(self):
        return self.schcd

    class Meta:
        db_table = 'school_info'
        managed = False
