# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-02-24 09:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ElementarySchool', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schoolinfo',
            options={'managed': False},
        ),
    ]
